name: "OpenHarmony Build Action"
description: "GitHub Action for building OpenHarmony v4.1/SDK v11 applications"

inputs:
  working-directory:
    description: "Working directory relative to repository root"
    required: false
    default: "."
  install-dependencies:
    description: "Install dependencies using ohpm install --all"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ ! -d "${{ inputs.working-directory }}" ]; then
          echo "::error::Working directory does not exist: ${{ inputs.working-directory }}"
          exit 1
        fi

    - name: Validate Runner OS
      shell: bash
      run: |
        if [ "$(uname)" != "Darwin" ]; then
          echo "::error::This action only supports macOS runners. Please use runs-on: macos-latest in your workflow."
          exit 1
        fi

    - name: Set up environment variables
      shell: bash
      run: |
        echo "CMD_PATH=$HOME/command-line-tools" >> $GITHUB_ENV
        echo "PROJECT_PATH=$(pwd)/${{ inputs.working-directory }}" >> $GITHUB_ENV

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.20.1"

    - name: Verify Project Structure
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ ! -f "./hvigorw" ]; then
          echo "::error::hvigorw not found in the root of the project."
          exit 1
        fi

    - name: Setup .npmrc File
      shell: bash
      run: |
        if [ ! -f "$HOME/.npmrc" ]; then
          touch $HOME/.npmrc
          echo "@ohos:registry=https://repo.harmonyos.com/npm/" >> $HOME/.npmrc
        fi

    - name: Setup OpenHarmony SDK
      uses: openharmony-rs/setup-ohos-sdk@v0.1
      with:
        version: "4.1"
        cache: true
        fixup-path: true

    - name: Setup command-line-tools
      shell: bash
      run: ${{ github.action_path }}/resource/cmd-tools/sdk-11/installer.sh
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        CMD_PATH: ${{ env.CMD_PATH }}
        PROJECT_PATH: ${{ env.PROJECT_PATH }}

    - name: Install Dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::Installing dependencies"
        ohpm install --all
        echo "::endgroup::"
